### ISSUE TITLE
Proposal: leverage .tmp_update/updater to auto convert stock SD to OnionOS 

### ISSUE THREAD

**Issue by UpdogUpdogUpdog** [jimgraygit/OnionOS#10]
Discord conversations today around 11:30-11:40am Eastern brought up some interesting thoughts.

If OnionOS installation is as simple as placing a zip of the contents and a .sh script into .tmp_update/updater, you could reduce install complexity by automating the entire process upon boot after copying it to the SD. 

It would be equally nice to zip a copy of the stock SD layout for safe keeping by the user should they ever want to revert.

**Comment by jimgraygit** [comment]
We are using Chive installer now, especially since Onion will have add-on packages in the future
