### ISSUE TITLE
Proposal: Store saves/states in content directories

### ISSUE THREAD

**Issue by jmaroeder** [jimgraygit/OnionOS#11]
.srm and .state files are currently saved in RetroArch/.retroarch/saves and RetroArch/.retroarch/states respectively, regardless of core. I think it would be helpful to keep them in either a separate root-level directory, or in their respective Roms subdirectories.

This will serve two purposes:
- Make it easier to keep saves when upgrading Onion
- Prevent problems in the event that roms from different systems have the exact same name

**Comment by jimgraygit** [comment]
Done in next update
