### ISSUE TITLE
Remarks from Poligraf

### ISSUE THREAD

**Issue by Sichroteph** [jimgraygit/OnionOS#6]
Poligraf regrets the removal of some standalone emulators : 
" fceumm and a bump on picodrive from memory
And I think we are missing the Atari cores.
And fuse should be standalone like god intended "

**Comment by Sichroteph** [comment]
I think it would be nice, a bit like the "buckup" folder, to leave the rest of the emulators there in case of special need.

**Comment by jimgraygit** [comment]
Onion is fully Retroarch based.
