### ISSUE TITLE
Fussy tweaks

### ISSUE THREAD

**Issue by rogalian** [jimgraygit/OnionOS#7]
SMS is better ran with genesis_plus_gx and the crop-side-borders option. Normal2x. (Use Grid2x for GG only)

FC should have "display horizontal overscan" disabled. Normal2x gives a better result than Normal4x - it's not as pin sharp, but it doesn't corrupt 45 degree lines as badly. (Normal2x_Width is better again, but I suspect the jump from 4x to 2x_Width is more extreme than people looking for crisp LCD pixels would like)

MD. Normal2x.

PSX - disable all enhanced resolution settings as default. Device can handle PSX well, but ER is hit and miss. Better off as a default.

Arcade: Aspect Ratio = 4:3, Crop Overscan = OFF

**Comment by jimgraygit** [comment]
did about 80% of this, thanks!
